name: drawable_example
description: Demonstrates how to use the drawable plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: '>=1.26.0-17.5.pre'

dependencies:
  drawable:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true